#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AirMedia.Resource", IsApplication=true)]

namespace AirMedia
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Resource.String.ApplicationName = global::AirMedia.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::AirMedia.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_left_to_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_in_right_to_left = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int slide_out_left_to_right = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int slide_out_right_to_left = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int centered = 2130771972;
			
			// aapt resource value: 0x7f01000c
			public const int clipPadding = 2130771980;
			
			// aapt resource value: 0x7f010005
			public const int fillColor = 2130771973;
			
			// aapt resource value: 0x7f01000d
			public const int footerColor = 2130771981;
			
			// aapt resource value: 0x7f010010
			public const int footerIndicatorHeight = 2130771984;
			
			// aapt resource value: 0x7f01000f
			public const int footerIndicatorStyle = 2130771983;
			
			// aapt resource value: 0x7f010011
			public const int footerIndicatorUnderlinePadding = 2130771985;
			
			// aapt resource value: 0x7f01000e
			public const int footerLineHeight = 2130771982;
			
			// aapt resource value: 0x7f010012
			public const int footerPadding = 2130771986;
			
			// aapt resource value: 0x7f010007
			public const int orientation = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int pageColor = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int radius = 2130771976;
			
			// aapt resource value: 0x7f010014
			public const int selectedBold = 2130771988;
			
			// aapt resource value: 0x7f010013
			public const int selectedColor = 2130771987;
			
			// aapt resource value: 0x7f010009
			public const int snap = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int strokeColor = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int strokeWidth = 2130771979;
			
			// aapt resource value: 0x7f010015
			public const int textColor = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int textSize = 2130771990;
			
			// aapt resource value: 0x7f010017
			public const int titlePadding = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int topPadding = 2130771992;
			
			// aapt resource value: 0x7f010000
			public const int vpiCirclePageIndicatorStyle = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int vpiTabPageIndicatorStyle = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int vpiTabTextStyle = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int vpiTitlePageIndicatorStyle = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f090000
			public const int default_circle_indicator_centered = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int default_circle_indicator_snap = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int default_title_indicator_selected_bold = 2131296258;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060012
			public const int default_circle_indicator_fill_color = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int default_circle_indicator_page_color = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int default_circle_indicator_stroke_color = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int default_title_indicator_footer_color = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int default_title_indicator_selected_color = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int default_title_indicator_text_color = 2131099671;
			
			// aapt resource value: 0x7f060003
			public const int holo_blue_bright = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int holo_blue_dark = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int holo_blue_light = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int holo_blue_light_translucent = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int light_theme_text_color = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int log_color_debug = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int log_color_error = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int log_color_info = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int log_color_verbose = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int log_color_warning = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int vpi__background_holo_dark = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int vpi__background_holo_light = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int vpi__bright_foreground_disabled_holo_dark = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int vpi__bright_foreground_disabled_holo_light = 2131099663;
			
			// aapt resource value: 0x7f06000c
			public const int vpi__bright_foreground_holo_dark = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int vpi__bright_foreground_holo_light = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int vpi__bright_foreground_inverse_holo_dark = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int vpi__bright_foreground_inverse_holo_light = 2131099665;
			
			// aapt resource value: 0x7f060018
			public const int vpi__dark_theme = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int vpi__light_theme = 2131099673;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f0b0000
			public const int default_circle_indicator_radius = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int default_circle_indicator_stroke_width = 2131427329;
			
			// aapt resource value: 0x7f0b0002
			public const int default_title_indicator_clip_padding = 2131427330;
			
			// aapt resource value: 0x7f0b0004
			public const int default_title_indicator_footer_indicator_height = 2131427332;
			
			// aapt resource value: 0x7f0b0005
			public const int default_title_indicator_footer_indicator_underline_padding = 2131427333;
			
			// aapt resource value: 0x7f0b0003
			public const int default_title_indicator_footer_line_height = 2131427331;
			
			// aapt resource value: 0x7f0b0006
			public const int default_title_indicator_footer_padding = 2131427334;
			
			// aapt resource value: 0x7f0b0007
			public const int default_title_indicator_text_size = 2131427335;
			
			// aapt resource value: 0x7f0b0008
			public const int default_title_indicator_title_padding = 2131427336;
			
			// aapt resource value: 0x7f0b0009
			public const int default_title_indicator_top_padding = 2131427337;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_player_ff_selector = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_player_play_selector = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_player_rew_selector = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int custom_tab_indicator_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int custom_tab_indicator_selected = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int custom_tab_indicator_selected_focused = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int custom_tab_indicator_selected_pressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int custom_tab_indicator_unselected = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int custom_tab_indicator_unselected_focused = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int custom_tab_indicator_unselected_pressed = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_action_edit = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_action_new = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_action_remove = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_audio_file = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_drawer = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_floppy = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_list = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_log_pause = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_log_start = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_player_ff = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_player_ff_colored = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_player_pause = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_player_pause_colored = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_player_play = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_player_play_colored = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_player_rew = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_player_rew_colored = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_share = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int Icon = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int list_item_color_selector = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int monoandroidsplash = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int toggle_log_button_pause = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int toggle_log_button_start = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int toggle_log_refresh_selector = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int vpi__tab_indicator = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int vpi__tab_selected_focused_holo = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int vpi__tab_selected_holo = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int vpi__tab_selected_pressed_holo = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int vpi__tab_unselected_focused_holo = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int vpi__tab_unselected_holo = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int vpi__tab_unselected_pressed_holo = 2130837544;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08002a
			public const int ActionEdit = 2131230762;
			
			// aapt resource value: 0x7f08002b
			public const int ActionNew = 2131230763;
			
			// aapt resource value: 0x7f080029
			public const int ActionRemove = 2131230761;
			
			// aapt resource value: 0x7f080028
			public const int ActionRename = 2131230760;
			
			// aapt resource value: 0x7f08000f
			public const int actionPanel = 2131230735;
			
			// aapt resource value: 0x7f080027
			public const int artist = 2131230759;
			
			// aapt resource value: 0x7f080023
			public const int buttonDetails = 2131230755;
			
			// aapt resource value: 0x7f08001a
			public const int buttonPlayerFF = 2131230746;
			
			// aapt resource value: 0x7f080019
			public const int buttonPlayerPlay = 2131230745;
			
			// aapt resource value: 0x7f080018
			public const int buttonPlayerRewind = 2131230744;
			
			// aapt resource value: 0x7f080011
			public const int buttonSave = 2131230737;
			
			// aapt resource value: 0x7f080010
			public const int buttonShare = 2131230736;
			
			// aapt resource value: 0x7f080007
			public const int contentView = 2131230727;
			
			// aapt resource value: 0x7f080005
			public const int drawerLayout = 2131230725;
			
			// aapt resource value: 0x7f080000
			public const int horizontal = 2131230720;
			
			// aapt resource value: 0x7f08001b
			public const int indicatorError = 2131230747;
			
			// aapt resource value: 0x7f08001c
			public const int indicatorErrorTitle = 2131230748;
			
			// aapt resource value: 0x7f080021
			public const int indicatorEventTitle = 2131230753;
			
			// aapt resource value: 0x7f08001f
			public const int indicatorInfo = 2131230751;
			
			// aapt resource value: 0x7f080020
			public const int indicatorInfoTitle = 2131230752;
			
			// aapt resource value: 0x7f080024
			public const int indicatorLeft = 2131230756;
			
			// aapt resource value: 0x7f080025
			public const int indicatorRight = 2131230757;
			
			// aapt resource value: 0x7f08001d
			public const int indicatorWarning = 2131230749;
			
			// aapt resource value: 0x7f08001e
			public const int indicatorWarningTitle = 2131230750;
			
			// aapt resource value: 0x7f080022
			public const int input = 2131230754;
			
			// aapt resource value: 0x7f080008
			public const int leftDrawer = 2131230728;
			
			// aapt resource value: 0x7f080012
			public const int listDisplaySwitch = 2131230738;
			
			// aapt resource value: 0x7f08000b
			public const int logEntryCountIndicator = 2131230731;
			
			// aapt resource value: 0x7f080013
			public const int logLevelSpinner = 2131230739;
			
			// aapt resource value: 0x7f080009
			public const int logPanelContainer = 2131230729;
			
			// aapt resource value: 0x7f080002
			public const int none = 2131230722;
			
			// aapt resource value: 0x7f080017
			public const int playerControlsPanel = 2131230743;
			
			// aapt resource value: 0x7f080006
			public const int playerView = 2131230726;
			
			// aapt resource value: 0x7f080026
			public const int progressBar = 2131230758;
			
			// aapt resource value: 0x7f08000e
			public const int progressPanel = 2131230734;
			
			// aapt resource value: 0x7f080014
			public const int seekBar = 2131230740;
			
			// aapt resource value: 0x7f08000d
			public const int toggleLogRefreshButton = 2131230733;
			
			// aapt resource value: 0x7f08000a
			public const int topBar = 2131230730;
			
			// aapt resource value: 0x7f08000c
			public const int topBarProgressIndicator = 2131230732;
			
			// aapt resource value: 0x7f080016
			public const int trackInfo = 2131230742;
			
			// aapt resource value: 0x7f080015
			public const int trackInfoPanel = 2131230741;
			
			// aapt resource value: 0x7f080003
			public const int triangle = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int underline = 2131230724;
			
			// aapt resource value: 0x7f080001
			public const int vertical = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0a0000
			public const int default_circle_indicator_orientation = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int default_title_indicator_footer_indicator_style = 2131361793;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Activity_MainView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Fragment_AudioLibrary = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Fragment_InAppLogging = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Fragment_PlayerFacade = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Fragment_PlaylistDetails = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Fragment_PlaylistsView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int View_DrawerNavigationItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int View_FragmentContainer = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int View_InAppLogPanel = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int View_InputField = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int View_LogEntry = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int View_PlaylistItem = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int View_Progress_Panel = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int View_TrackItem = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0c0000
			public const int context_menu_audio_library = 2131492864;
			
			// aapt resource value: 0x7f0c0001
			public const int context_menu_playlists_view = 2131492865;
			
			// aapt resource value: 0x7f0c0002
			public const int menu_playlists_details = 2131492866;
			
			// aapt resource value: 0x7f0c0003
			public const int menu_playlists_view = 2131492867;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050018
			public const int dialog_create_playlist_confirm = 2131034136;
			
			// aapt resource value: 0x7f050016
			public const int dialog_create_playlist_title = 2131034134;
			
			// aapt resource value: 0x7f05002b
			public const int dialog_log_details_accept_text = 2131034155;
			
			// aapt resource value: 0x7f05002a
			public const int dialog_log_details_title = 2131034154;
			
			// aapt resource value: 0x7f05001a
			public const int dialog_remove_playlists_message = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int dialog_remove_playlists_title = 2131034137;
			
			// aapt resource value: 0x7f050017
			public const int dialog_rename_playlist_title = 2131034135;
			
			// aapt resource value: 0x7f05002f
			public const int dialog_save_file_title = 2131034159;
			
			// aapt resource value: 0x7f050031
			public const int dialog_title_send_log_via = 2131034161;
			
			// aapt resource value: 0x7f05002d
			public const int error_cant_create_log_file = 2131034157;
			
			// aapt resource value: 0x7f05001c
			public const int error_cant_create_playlist = 2131034140;
			
			// aapt resource value: 0x7f050025
			public const int error_cant_play_playlists = 2131034149;
			
			// aapt resource value: 0x7f050023
			public const int error_cant_play_playlists_no_audio = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int error_cant_play_playlists_no_playlists = 2131034148;
			
			// aapt resource value: 0x7f05001f
			public const int error_cant_remove_playlists = 2131034143;
			
			// aapt resource value: 0x7f05001d
			public const int error_cant_rename_playlist = 2131034141;
			
			// aapt resource value: 0x7f05002c
			public const int error_cant_save_log_file = 2131034156;
			
			// aapt resource value: 0x7f050021
			public const int error_cant_start_audio_library_playback = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int error_cant_start_audio_library_playback_no_audio = 2131034146;
			
			// aapt resource value: 0x7f050020
			public const int error_cant_update_playlists = 2131034144;
			
			// aapt resource value: 0x7f05001b
			public const int error_empty_playlist_name = 2131034139;
			
			// aapt resource value: 0x7f05001e
			public const int error_generic_cant_rename_playlist = 2131034142;
			
			// aapt resource value: 0x7f050030
			public const int error_log_dir_not_available = 2131034160;
			
			// aapt resource value: 0x7f05000c
			public const int hint_close_main_drawer = 2131034124;
			
			// aapt resource value: 0x7f050011
			public const int hint_create_playlist = 2131034129;
			
			// aapt resource value: 0x7f050014
			public const int hint_edit_playlist = 2131034132;
			
			// aapt resource value: 0x7f05000b
			public const int hint_open_main_drawer = 2131034123;
			
			// aapt resource value: 0x7f050015
			public const int hint_pick_playlist_tracks = 2131034133;
			
			// aapt resource value: 0x7f050012
			public const int hint_remove_playlist = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int hint_rename_playlist = 2131034131;
			
			// aapt resource value: 0x7f050006
			public const int message_audio_library_empty = 2131034118;
			
			// aapt resource value: 0x7f05002e
			public const int message_log_file_saved = 2131034158;
			
			// aapt resource value: 0x7f050008
			public const int message_playlist_empty = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int message_playlists_list_empty = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int message_progress = 2131034114;
			
			// aapt resource value: 0x7f05000d
			public const int title_audio_library = 2131034125;
			
			// aapt resource value: 0x7f050003
			public const int title_list_empty = 2131034115;
			
			// aapt resource value: 0x7f050027
			public const int title_log_expand_toggle = 2131034151;
			
			// aapt resource value: 0x7f050026
			public const int title_log_level = 2131034150;
			
			// aapt resource value: 0x7f050010
			public const int title_main_view = 2131034128;
			
			// aapt resource value: 0x7f050009
			public const int title_navigation_item_media_library = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int title_navigation_item_playlists = 2131034122;
			
			// aapt resource value: 0x7f05000f
			public const int title_playlist_details = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int title_playlists_view = 2131034126;
			
			// aapt resource value: 0x7f050028
			public const int title_save_log = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int title_share_log = 2131034153;
			
			// aapt resource value: 0x7f050004
			public const int title_unknown_artist = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int title_unknown_track = 2131034117;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f07000a
			public const int AppBaseTheme = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int AppTheme = 2131165195;
			
			// aapt resource value: 0x7f070000
			public const int AppTheme_Text = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int AppTheme_Text_Large = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int AppTheme_Text_Small = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int CustomCirclePageIndicator = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int CustomTabPageIndicator = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int CustomTabPageIndicator_Text = 2131165192;
			
			// aapt resource value: 0x7f070005
			public const int CustomTitlePageIndicator = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int LogText = 2131165187;
			
			// aapt resource value: 0x7f070009
			public const int Mono_Android_Theme_Splash = 2131165193;
			
			// aapt resource value: 0x7f070004
			public const int StyledIndicators = 2131165188;
			
			// aapt resource value: 0x7f070012
			public const int TextAppearance_TabPageIndicator = 2131165202;
			
			// aapt resource value: 0x7f07000c
			public const int Theme_PageIndicatorDefaults = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int Widget = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int Widget_CirclePageIndicator = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int Widget_TabPageIndicator = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int Widget_TabPageIndicator_Text = 2131165201;
			
			// aapt resource value: 0x7f07000f
			public const int Widget_TitlePageIndicator = 2131165199;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CirclePageIndicator = new int[] {
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 0
			public const int CirclePageIndicator_centered = 0;
			
			// aapt resource value: 1
			public const int CirclePageIndicator_fillColor = 1;
			
			// aapt resource value: 3
			public const int CirclePageIndicator_orientation = 3;
			
			// aapt resource value: 2
			public const int CirclePageIndicator_pageColor = 2;
			
			// aapt resource value: 4
			public const int CirclePageIndicator_radius = 4;
			
			// aapt resource value: 5
			public const int CirclePageIndicator_snap = 5;
			
			// aapt resource value: 6
			public const int CirclePageIndicator_strokeColor = 6;
			
			// aapt resource value: 7
			public const int CirclePageIndicator_strokeWidth = 7;
			
			public static int[] TitlePageIndicator = new int[] {
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992};
			
			// aapt resource value: 0
			public const int TitlePageIndicator_clipPadding = 0;
			
			// aapt resource value: 1
			public const int TitlePageIndicator_footerColor = 1;
			
			// aapt resource value: 4
			public const int TitlePageIndicator_footerIndicatorHeight = 4;
			
			// aapt resource value: 3
			public const int TitlePageIndicator_footerIndicatorStyle = 3;
			
			// aapt resource value: 5
			public const int TitlePageIndicator_footerIndicatorUnderlinePadding = 5;
			
			// aapt resource value: 2
			public const int TitlePageIndicator_footerLineHeight = 2;
			
			// aapt resource value: 6
			public const int TitlePageIndicator_footerPadding = 6;
			
			// aapt resource value: 8
			public const int TitlePageIndicator_selectedBold = 8;
			
			// aapt resource value: 7
			public const int TitlePageIndicator_selectedColor = 7;
			
			// aapt resource value: 9
			public const int TitlePageIndicator_textColor = 9;
			
			// aapt resource value: 10
			public const int TitlePageIndicator_textSize = 10;
			
			// aapt resource value: 11
			public const int TitlePageIndicator_titlePadding = 11;
			
			// aapt resource value: 12
			public const int TitlePageIndicator_topPadding = 12;
			
			public static int[] ViewPagerIndicator = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int ViewPagerIndicator_vpiCirclePageIndicatorStyle = 0;
			
			// aapt resource value: 2
			public const int ViewPagerIndicator_vpiTabPageIndicatorStyle = 2;
			
			// aapt resource value: 3
			public const int ViewPagerIndicator_vpiTabTextStyle = 3;
			
			// aapt resource value: 1
			public const int ViewPagerIndicator_vpiTitlePageIndicatorStyle = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
